language: python
python:
  - "3.5"

before_install:
  - sudo apt-get update -qq

install:
  - python setup.py -q install
  - pip install -r test_requirements.txt

before_script:
  - mysql -e 'CREATE DATABASE test_db CHARACTER SET utf8;'

script:
  - make test

notifications:
  email: false
  webhooks: http://finebot.herokuapp.com/hubot/travis/?room=30565_platform@conf.hipchat.com
